### ISSUE TITLE
Feature request - Door state sensor

### ISSUE THREAD

**Issue by AnthonyBe** [williamschey/hassio-omlet-smartcoop-door#5]
Hi, 

You've probably got this on your list, but I just wanted to specifically request a door state sensor so that I have a easy way to see historical state changes, e.g. when did door open, when did door close, etc.

Also, is it possible to distinguish between events triggered by schedule versus manually triggered? E.g. is it possible to differentiate between 'door opening' triggered by light level in the morning, versus 'door opening' triggered by someone clicking 'open door' in the app?

Cheers, 
Anthony

**Comment by dpwood** [comment]
Hi Anthony,

It isn't possible to discern the reason for the door state changing unfortunately. The API only provides the new state of the door, not the reason, or any other precursor events like the light level or time being reached.

The door entity (The cover.XYZ_door entity) has a state attribute, which will tell you the same thing a door state sensor would. If you look for it in the logbook, you'll see the history of it opening and closing. We've also got an entity exposed for "Last Close Time" and another for "Last Open Time", which hopefully gives you all the insight you need?

If you haven't already done so, update to v0.9.1 and the entities I've described should be there.

Kind Regards,
Dave

**Comment by AnthonyBe** [comment]
Thanks Dave! And apologies, I should've stated initially that I was using 0.9.1 of the integration.

Yep, I can get the most important data I want (time door opened, time door closed) from the cover entity History log.
Is the cover entity only generating those 2 states? I seem to recall from the original Community thread (https://community.home-assistant.io/t/omlet-auto-door-for-chicken-coop/191283/77) that there were a few more states that the Omlet API/Webhook exposed. Not as important as Open and Closed, but just curious for 'completeness'.

Re. documenting the trigger mechanism of the door state change, thanks for confirming that that data isn't exposed. I guess that's something we go back and ask Omlet Dave for :)

**Comment by dpwood** [comment]
Hi,

To be honest, that's more states than I was aware of. I see why you want more detail. The cover entity understands open, closed, opening and closing. You'll see those in the logbook. Currently we we map the Omlet door states with:

```
        if state == "stopping":
            return #Ignore stopping state, previous state persists until we get a new actual position
        self._attr_is_closed = state == "closed"
        self._attr_is_closing = state in ("closing", "closepending")
        self._attr_is_opening = state in ("opening", "openpending")
```
All other states will be considered "open" which I don't think is unreasonable. According to that previous post (would love some documentation here) these states are:

- open
- unknown
- calibrating
- openstopped
- closestopped 


Regarding exposing the raw state value. There are two options:

1. Add a new door sensor entity for the raw state value. This might be a little extreme, but would give you everything you want, plus logbook entries.
2. Add an attribute to the door cover, so that you can see the raw state and use it in automations, but it's part of the cover entity rather than an entirely new entity. The drawback is it's not in the logbook. I would suggest doing the same for the light entity too.

![image](https://github.com/user-attachments/assets/a4765dc2-c5d4-4a01-a3ff-52fb6f6891c7)

What do you think?

Kind Regards,
Dave

**Comment by williamschey** [comment]
Hi @AnthonyBe,

Added the raw_state attribute to the cover. Let me know if this does not suffice.

Cheers,
Will
